### ISSUE TITLE
Version One connection exception with Tokens

### ISSUE THREAD

**Issue by jcreel** [TAMULib/ProjectManagementService#110]
```
com.versionone.apiclient.exceptions.ConnectionException: 
HTTP/1.1 401 Unauthorized error code: 401 Could not authenticate. The VersionOne credentials may be incorrect or the access tokens may have expired.
	at com.versionone.apiclient.V1Connector.manageErrors(V1Connector.java:375)
	at com.versionone.apiclient.V1Connector.getData(V1Connector.java:320)
	at com.versionone.apiclient.Services.retrieve(Services.java:135)
	at edu.tamu.app.service.manager.VersionOneService.getRemoteProject(VersionOneService.java:79)
	at edu.tamu.app.cache.service.RemoteProjectsScheduledCacheService.update(RemoteProjectsScheduledCacheService.java:55)
	at edu.tamu.app.cache.service.AbstractScheduledCacheService.schedule(AbstractScheduledCacheService.java:27)
	at edu.tamu.app.cache.service.RemoteProjectsScheduledCacheService.schedule(RemoteProjectsScheduledCacheService.java:41)
	at edu.tamu.app.model.repo.impl.RemoteProjectManagerRepoImpl.lambda$updateCache$0(RemoteProjectManagerRepoImpl.java:62)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kaladay** [comment]
Cannot Reproduce what triggered this outside of intentionally setting an invalid token.
